version: "3"

vars:
  PYTEST_ARGS: ""

tasks:
  convert-to-parquet:
    desc: "Convert the data to Parquet"
    aliases:
      - parquet
    cmds:
      - uv run python ./scripts/convert/convert_data_into_parquet.py

  convert-to-csv:
    desc: "Convert the data to CSV"
    aliases:
      - csv
    cmds:
      - uv run python ./scripts/convert/convert_data_into_csv.py

  convert-to-json:
    desc: "Convert the data to JSON"
    aliases:
      - json
    cmds:
      - uv run python ./scripts/convert/convert_data_into_json.py

  clean:
    desc: "Clean the data"
    aliases:
      - c
      - clear
    cmds:
      - rm -rf data/parquet/*
      - rm -rf data/csv/*
      - rm -rf data/json/*
